<?php

/**
 * @file
 * Implements hooks and globally accesible functions.
 *
 * @author Goce Shutinoski <gsutinoski@propeople.dk>
 * @author Lachezar Valchev <lachezar@propeople.dk>
 */

/**
 * Implements hook_libraries_info().
 */
function columnizer_libraries_info() {
  $libraries['columnizer'] = array(
    'name' => 'Columnizer',
    'vendor url' => 'http://welcome.totheinter.net/columnizer-jquery-plugin/',
    'download url' => 'https://github.com/adamwulf/Columnizer-jQuery-Plugin',
    'version arguments' => array(
      'file' => 'jquery.columnizer.min.js',
      // Version 1.6.0
      'pattern' => '/version (\d+\.+\d+)/',
      'lines' => 5,
    ),
    'files' => array(
      'js' => array(
        'jquery.columnizer.min.js',
      ),
    ),
  );

  return $libraries;
}
