image: docker:latest

before_script:
  - apk add --no-cache curl jq python py-pip bash findutils git zlib-dev openssh-client php7 php7-json php7-phar php7-iconv php7-openssl php7-mbstring php7-simplexml php7-tokenizer php7-xmlwriter php7-ctype php7-curl php7-dom
  - pip install --upgrade pip
  - pip install awscli

stages:
  - test
  - build
  - deploy

variables:
  PROJECT_NAME: "sof"
  REPO_PATH: "/FFW-CSO/D7/skoleforaeldre"

code-quality-checks:
  stage: test
  variables:
    BUILDS_PATH: "$REPO_PATH"
  script:
    - curl --silent --show-error https://getcomposer.org/installer | php
    - echo "Code Sniffer"
    - php composer.phar require drupal/coder
    - ./vendor/bin/phpcs --config-set installed_paths /builds$REPO_PATH/vendor/drupal/coder/coder_sniffer
    - ./vendor/bin/phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme /builds$REPO_PATH/docroot/sites/all/modules/custom/

build:
  stage: build
  variables:
    PNAME: "$PROJECT_NAME"
    PURL: "$CI_COMMIT_REF_SLUG"
  script:
    - /bin/bash ecsrun.sh $PNAME $PURL build

deploy:develop:
  stage: deploy
  variables:
    PNAME: "$PROJECT_NAME"
    PURL: "$CI_COMMIT_REF_SLUG"
  environment:
    name: "$PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    url: "http://$PROJECT_NAME.demo.ffw-cs.com"
  only:
    - develop
  script:
    - /bin/bash ecsrun.sh $PNAME $PURL deploydev

deploy:feature:
  stage: deploy
  variables:
    PNAME: "$PROJECT_NAME"
    PURL: "$CI_COMMIT_REF_SLUG"
  environment:
    name: "$PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    url: "http://$PROJECT_NAME-$CI_COMMIT_REF_SLUG.demo.ffw-cs.com"
    on_stop: stop:feature
  only:
    - /^feature.*$/
  script:
    - /bin/bash ecsrun.sh $PNAME $PURL deployfeat 

stop:feature:
  stage: deploy
  variables:
    PNAME: "$PROJECT_NAME"
    PURL: "$CI_COMMIT_REF_SLUG"
  when: manual
  only:
    - /^feature.*$/
  environment:
    name: "$PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    url: "http://$PROJECT_NAME-$CI_COMMIT_REF_SLUG.demo.ffw-cs.com"
    action: stop
  script:
    - /bin/bash ecsrun.sh $PNAME $PURL stopfeat
