image: wodby/drupal-php:5.6

stages:
 - build
 - test
 - deploy

code-quality-checks:
  stage: test
  script:
   - echo "Code Sniffer"
   - composer require drupal/coder
   - ./vendor/bin/phpcs --config-set installed_paths /builds/FFW-CSO/D7/skoleforaeldre/vendor/drupal/coder/coder_sniffer
   - ./vendor/bin/phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme /builds/FFW-CSO/D7/skoleforaeldre/sites/all/modules/custom/
   - echo "Mess Detector"
   - composer require phpmd/phpmd
   - ./vendor/bin/phpmd . html codesize,unusedcode,naming,design,cleancode,controversial --reportfile docs/phpmd.html --exclude vendor --suffixes php,module,inc,install,profile,theme
