<?php

/**
 * Implements hook_libraries_info().
 */
function phpwkhtmltopdf_libraries_info() {
  return array(
    'phpwkhtmltopdf' => array(
      'name' => 'PHPWkHtmlToPdf',
      'vendor url' => 'https://github.com/mikehaertl/phpwkhtmltopdf',
      'download url' => 'https://github.com/mikehaertl/phpwkhtmltopdf/archive/2.0.1.tar.gz',
      'version arguments' => array(
        'file' => 'src/Pdf.php',
        'pattern' => '/version ([0-9\.\w-]+)/',
      ),
      'files' => array(
        'php' => array(
          'src/Pdf.php',
          'src/Image.php',
          'src/Command.php',
        ),
      ),
      'integration files' => array(
        // Add our custom wrapper class for backward compatibility.
        'phpwkhtmltopdf' => array(
          'lib/phpwkhtmltopdf.php',
        ),
      ),
      'dependencies' => array(
        'php-shellcommand (>=1.0.2)',
        'php-tmpfile (>=1.0.0)',
      ),
    ),
    'php-shellcommand' => array(
      'name' => 'php-shellcommand',
      'vendor url' => 'https://github.com/mikehaertl/php-shellcommand',
      'download url' => 'https://github.com/mikehaertl/php-shellcommand/archive/1.0.3.tar.gz',
      'version arguments' => array(
        'file' => 'src/Command.php',
        'pattern' => '/version ([0-9\.\w-]+)/',
      ),
      'files' => array(
        'php' => array(
          'src/Command.php',
        ),
      ),
    ),
    'php-tmpfile' => array(
      'name' => 'php-tmpfile',
      'vendor url' => 'https://github.com/mikehaertl/php-tmpfile',
      'download url' => 'https://github.com/mikehaertl/php-tmpfile/archive/1.0.0.tar.gz',
      'version arguments' => array(
        'file' => 'src/File.php',
        'pattern' => '/version ([0-9\.\w-]+)/',
      ),
      'files' => array(
        'php' => array(
          'src/File.php',
        ),
      ),
    ),
  );
}


/**
 * Loads the PHPWkHtmlToPdf library files and its dependencies.
 */
function phpwkhtmltopdf_libraries_load() {

}
