<?php

/**
 * @file
 * Implements hooks and globally accesible functions.
 *
 * @author Goce Shutinoski <gsutinoski@propeople.dk>
 */

/**
 * Implements hook_block_info().
 */
function sof_releases_page_teaser_block_info() {
  $blocks['sof_releases_page_teaser'] = array(
    'info' => t('SOF Releases page teaser block'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function sof_releases_page_teaser_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'sof_releases_page_teaser':
      $block['title'] = '';
      $block['content'] = _sof_releases_page_teaser_contents($delta);
      break;
  }

  return $block;
}

/**
 * Implements hook_block_configure().
 */
function sof_releases_page_teaser_block_configure($delta = '') {
  $form = array();

  switch ($delta) {
    case 'sof_releases_page_teaser':
      $dbvar_value = variable_get('sof_rpb', array('value' => '', 'format' => NULL));

      $form['sof_releases_page_teaser'] = array(
        '#type'     => 'text_format',
        '#title'    => 'Releases page teaser block content',
        '#definition' => 'Releases page teaser',
        '#default_value' => $dbvar_value['value'],
        '#weight'   => 1,
        '#format' => $dbvar_value['format'],
        '#required' => FALSE,
      );
      break;
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function sof_releases_page_teaser_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'sof_releases_page_teaser':
      variable_set('sof_rpb', array(
        'value' => $edit['sof_releases_page_teaser']['value'],
        'format' => $edit['sof_releases_page_teaser']['format'],
      ));
      break;
  }
}

/**
 * Block contents helper function.
 *
 * @param string $delta
 *   Block unique identifier.
 *
 * @return string
 *   Block contents html content.
 */
function _sof_releases_page_teaser_contents($delta) {
  switch ($delta) {
    case 'sof_releases_page_teaser':

      $dbvar_value = variable_get('sof_rpb', array('value' => '', 'format' => NULL));
      $output = $dbvar_value['value'];
      break;

  }

  return $output;
}
