<?php

/**
 * Implements hook_field_group_build_pre_render_alter().
 *
 * @see field_group.api.php
 */
function sof_general_tweaks_field_group_build_pre_render_alter(& $element) {

    //Add states for fieldgroups in publication content type
    if(isset($element['#form_id'])){
            if($element['#form_id'] == 'publication_node_form'){
        
                $element['group_upload']['#states'] = array(
                    'visible' => array(
                      'select[name="field_publication_file_type[' . LANGUAGE_NONE . ']"]' => array('value' => '1'),
                    ),
                    'expanded' => array(
                      'select[name="field_publication_file_type[' . LANGUAGE_NONE . ']"]' => array('value' => '1'),
                    ),
                );
                
                $element['group_generate_from_content']['#states'] = array(
                    'visible' => array(
                      'select[name="field_publication_file_type[' . LANGUAGE_NONE . ']"]' => array('value' => '2'),
                    ),
                    'expanded' => array(
                      'select[name="field_publication_file_type[' . LANGUAGE_NONE . ']"]' => array('value' => '2'),
                    ),
                );
                               
            }
    }


}


/**
 * Implements hook_field_extra_fields().
 */
function sof_general_tweaks_field_extra_fields() {
  
  //News deck
  //Additional fild for additional latest news   
  $extra['node']['news']['display']['additional_bottom_nodes'] = array(
    'label' => t('Additional bottom news'),
    'description' => t('Renders latest 3 news'),
    'weight' => 4,
    'visible' => FALSE,
  );
  
  //Recommended items deck
  //Additional fild for additional latest news   
  $extra['fieldable_panels_pane']['recommended_items_pane']['display']['overview_recommended_items'] = array(
    'label' => t('Overview'),
    'description' => t('Overview of the items in this section'),
    'weight' => 4,
  );
  
   //What we write about deck
   //Additional field for most read
   $extra['fieldable_panels_pane']['what_we_write_about_pane']['display']['most_read_nodes'] = array(
    'label' => t('Most read'),
    'description' => t('Most read nodes'),
    'weight' => 4,
   );
   //Additional field for most read
   $extra['fieldable_panels_pane']['what_we_write_about_pane']['display']['last_updated_nodes'] = array(
    'label' => t('Last updated'),
    'description' => t('Last updated nodes'),
    'weight' => 4,
   );
   
   return $extra;

}

/**
 * Implements hook_node_view().
 */
function sof_general_tweaks_node_view($node, $view_mode, $langcode) {
  
  $extrafields = field_extra_fields_get_display('node', $node->type, $view_mode);
  $extrafield_name = 'primary_selected_node';
  
  //Attach 'news_deck_latest_3_nodes' to the node as extra field
  if (isset($extrafields[$extrafield_name])
      && isset($extrafields[$extrafield_name]['visible'])
      && $extrafields[$extrafield_name]['visible']) {
          
    $node->content['additional_bottom_nodes'] = array(
      '#markup' => views_embed_view('news_deck_latest_3_nodes', 'news_deck_latest_three_news'),
    );
    
  }

}


/**
 * Implements hook_entity_view().
 */
function sof_general_tweaks_entity_view($entity, $type, $view_mode, $langcode) { 
  
  switch ($type) {
      
      case 'fieldable_panels_pane':
        
        //Attach 'recommended_items_overview' view to the panel pane as extra field
        if($entity->bundle == 'recommended_items_pane') { 
            $entity->content['overview_recommended_items'] = array(
              '#type' => 'item',
              '#title'  => t('Overview'),
              '#markup' => views_embed_view('recommended_items_overview', 'recommended_items_overview'),
            );
        }
        //Attach 'we_are_writing_about_additional_displays' view to the panel pane as extra field
        else if($entity->bundle == 'what_we_write_about_pane'){
            $entity->content['most_read_nodes'] = array(
              '#type' => 'item',
              '#title'  => t('Most read'),
              '#markup' => views_embed_view('we_are_writing_about_additional_displays', 'most_popular'),
            );
            $entity->content['last_updated_nodes'] = array(
              '#type' => 'item',
              '#title'  => t('Latest updated'),
              '#markup' => views_embed_view('we_are_writing_about_additional_displays', 'latest_updated'),
            );
        }
      break;
  }
  
}

/**
 * Implements hook_apachesolr_index_document_build_ENTITY_TYPE().
 * 
 * @see apachesolr.api.php for additional info
 */
function sof_general_tweaks_apachesolr_index_document_build_node(ApacheSolrDocument $document, $entity, $env_id) {
    
  $node = node_load($entity->vid);
  
  //Render the node and strip all html tags from it
  $full_node_html = drupal_html_to_text(drupal_render(node_view($node)));
  
  //Add new field for drupal search
  $document->addField('ts_custom_text', $full_node_html);
         
}

/**
 * Implements hook_apachesolr_query_prepare().
 *  
 * @see apachesolr.api.php for additional info
 */
function sof_general_tweaks_apachesolr_query_prepare(DrupalSolrQueryInterface $query) {
  
  //Make ts_custom_text custom field searchable  
  $query->addParam('fl', 'ts_custom_text');
  
}

/**
 * Implements hook_apachesolr_field_name_map_alter()
 *
 * @see apachesolr.api.php for additional info
 */
function sof_general_tweaks_apachesolr_field_name_map_alter(array &$map) {
  
  //Add human readable name for our custom field    
  $map['ts_custom_text'] = t('The full node object');
}
