<?php

/**
 * @file
 * Implements hooks and globally accesible functions.
 *
 * @author Goce Shutinoski <gsutinoski@propeople.dk>
 * @author Lachezar Valchev <lachezar@propeople.dk>
 */

/**
 * Adding new style for Seven admin theme.
 */
function customadmincss_preprocess_html(&$variables) {
  // Add conditional stylesheets for admin pages on admin theme.
  if (arg(0) == "admin") {
    // Reference your current admin theme.
    $theme_path = drupal_get_path('theme', 'seven');
    // Reference your own stylesheet.
    drupal_add_css(drupal_get_path('module', 'customadmincss') . '/css/customadmincss.css', array('weight' => CSS_THEME));
  }
}
